In [2]:
import os
import pandas as pd
# ! pip install chardet

In [2]:
for file in os.listdir('./files'):
    with open(f'files/{file}', 'rb') as f:
        result = chardet.detect(f.read())
        print(result['encoding'])  # 인코딩 확인
    df = pd.read_csv(f'files/{file}', encoding=result['encoding'])
    df.to_csv(f'files2/{file}')

NameError: name 'chardet' is not defined

---

In [3]:
df_blink = pd.read_csv('files2/origin/blinker.csv')
df_blink.head()

/tmp/ipykernel_46752/3700200044.py:1: DtypeWarning: Columns (6,31) have mixed types. Specify dtype option on import or set low_memory=False.
  df_blink = pd.read_csv('files2/origin/blinker.csv')

,Unnamed: 0,시군코드,시군명,시도명,시군구명,도로종류,도로노선번호,도로노선명,도로노선방향,소재지도로명주소,...,점멸등운영여부,점멸등운영시작시각,점멸등운영종료시각,보행자작동신호기유무,잔여시간표시기유무,시각장애인용음향신호기유무,도로안내표지일련번호,관리기관명,관리기관전화번호,데이터기준일자
0,0,41210.0,광명시,경기도,광명시,시도,NaN,광명역로,3,NaN,...,N,00:00,00:00,N,N,N,NaN,경기도 광명시 도시교통과,02-2680-2585,2023-12-14
1,1,41210.0,광명시,경기도,광명시,시도,NaN,새빛공원로,3,NaN,...,Y,01:00,06:00,N,N,N,NaN,경기도 광명시 도시교통과,02-2680-2585,2023-12-14
2,2,41210.0,광명시,경기도,광명시,시도,NaN,새빛공원로,3,경기도 광명시 새빛공원로 10,...,Y,01:00,06:00,N,N,N,NaN,경기도 광명시 도시교통과,02-2680-2585,2023-12-14
3,3,41210.0,광명시,경기도,광명시,시도,NaN,양달로,3,NaN,...,Y,07:00,08:00,N,N,N,NaN,경기도 광명시 도시교통과,02-2680-2585,2023-12-14
4,4,41210.0,광명시,경기도,광명시,시도,NaN,일직로,3,NaN,...,Y,23:00,05:00,N,N,N,NaN,경기도 광명시 도시교통과,02-2680-2585,2023-12-14

In [43]:
# df_blink[df_blink['신호등구분'] == 2]['시군명'].unique()
df_blink[df_blink['신호등구분'] == 2].groupby('시군명').size()

시군명
구리시      880
남양주시    2339
오산시     1543
의정부시    2147
파주시      216
평택시        2
포천시      950
하남시     1682
dtype: int64

In [4]:
df_blink = df_blink[df_blink['시군명'] == '남양주시']
# print(df_blink['신호등구분'].unique())
df_blink = df_blink[df_blink['신호등구분'] < 3]
df_blink.drop(['Unnamed: 0'], axis = 1, inplace = True)
df_blink.to_csv('files2/refined/blinker.csv', index = False)
len(df_blink)

5389

In [17]:
#import pandas as pd
import glob

# 같은 폴더 내 모든 CSV 파일 합치기
file_list = glob.glob("files2/origin/*_data.csv")  # 경로에 맞게 수정

df_list = [pd.read_csv(f) for f in file_list]
df_all = pd.concat(df_list, ignore_index=True)
df_all = df_all[df_all['사고유형_대분류'] == '차대사람']
df_all = df_all[df_all['발생지시도'] == '서울']
df_all = df_all.dropna(subset=['경도','위도'])
print(len(df_all))
df_all = df_all[['발생년월일시', '주야', '요일', '발생지시군구', '사고유형_대분류', '가해자법규위반', '경도', '위도']]
df_all.rename(columns={
    '위도': 'Y_coord',
    '경도': 'X_coord',
    '발생지시군구' : 'district'
}, inplace=True)
# df_all.drop(['Unnamed: 0'], axis = 1, inplace = True)

df_all.to_csv('files2/final/accidents.csv', index = False)
df_all.head(1)

2002

          발생년월일시 주야 요일 district 사고유형_대분류      가해자법규위반     X_coord    Y_coord
7  2019-01-02 10  주  수       중구     차대사람  안전운전 의무 불이행  126.995299  37.568449

In [59]:
#import pandas as pd
import glob

# 같은 폴더 내 모든 CSV 파일 합치기
file_list = glob.glob("files2/origin/*_data.csv")  # 경로에 맞게 수정

df_list = [pd.read_csv(f) for f in file_list]

df_all = pd.concat(df_list, ignore_index=True)
df_all = df_all[df_all['사고유형_대분류'] == '차대사람']
df_all = df_all[df_all['발생지시군구'] == '']
df_all
print(len(df_all))
df_all.drop(['Unnamed: 0'], axis = 1, inplace = True)
# df_all.to_csv('files2/refined/data.csv', index = False)
df_all.head(1)

160

,발생년,발생년월일시,주야,요일,사망자수,부상자수,중상자수,경상자수,부상신고자수,발생지시도,...,피해자_당사자종별_대분류,발생위치X(UTMK),발생위치Y(UTMK),발생위치X,발생위치Y,발생분,당사자종별_1당_대분류,당사자종별_1당,당사자종별_2당_대분류,당사자종별_2당
96,2019,2019-01-13 11,주,일,1,0.0,0,0,0,경기,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
#import pandas as pd
import glob

# 같은 폴더 내 모든 CSV 파일 합치기
file_list = glob.glob("files2/origin/*_data.csv")  # 경로에 맞게 수정
file_list.sort()
print(file_list)
# df_all = pd.DataFrame()
# for _dfn in file_list:
#     _df = pd.read_csv(_dfn)
#     # df_all = pd.concat([df_all, _df])
#     # print(df_all)

df_list = [pd.read_csv(f) for f in file_list]
df_all = pd.concat(df_list, axis=1)
df_all
# df_clean_AB = df.dropna(subset=['경도','위도'])
# # df_all = df_all.dropna()
# # df_list[2]
# # df_all = df_all[df_all['사고유형_대분류'] == '차대사람']
# df_all = df_all[df_all['발생지시도'] == '서울']
# df_all[df_all['발생지시도'] == '서울']
# print(len(df_all))
# df_all.drop(['Unnamed: 0'], axis = 1, inplace = True)
# df_all.to_csv('files2/refined/data.csv', index = False)
# df_all.head(1)

['files2/origin/2012_2014_data.csv', 'files2/origin/2015_data.csv', 'files2/origin/2016_data.csv', 'files2/origin/2017_data.csv', 'files2/origin/2018_data.csv', 'files2/origin/2019_data.csv', 'files2/origin/2020_data.csv', 'files2/origin/2021_data.csv', 'files2/origin/2022_data.csv', 'files2/origin/2023_data.csv']

,Unnamed: 0,발생년,발생년월일시,발생분,주야,요일,사망자수,사상자수,중상자수,경상자수,...,사고유형,가해자법규위반,도로형태_대분류,도로형태,가해자_당사자종별,피해자_당사자종별,발생위치X,발생위치Y,경도,위도
0,0,2012,2012-05-09 01:00,10,야간,수,1,1,0,0,...,기타,안전운전 의무 불이행,단일로,기타단일로,건설기계,보행자,1015896.0,1885475.0,127.678579,36.967573
1,1,2012,2012-03-30 13:00,32,주간,금,1,1,0,0,...,기타,안전운전 의무 불이행,단일로,기타단일로,이륜차,없음,1089954.0,1651437.0,128.484013,34.853623
2,2,2012,2012-10-26 20:00,55,야간,금,1,2,1,0,...,기타,안전운전 의무 불이행,단일로,기타단일로,화물차,보행자,1181459.0,1784728.0,129.514309,36.042531
3,3,2012,2012-06-28 14:00,10,주간,목,1,1,0,0,...,공작물충돌,안전운전 의무 불이행,단일로,기타단일로,이륜차,없음,943961.0,1915763.0,126.868199,37.239046
4,4,2012,2012-06-18 04:00,15,야간,월,1,1,0,0,...,기타,안전운전 의무 불이행,단일로,기타단일로,이륜차,없음,974470.0,1970403.0,127.210265,37.732883
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14619,14619,2014,2014-07-05 16:00,30,주간,토,1,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14620,14620,2014,2014-07-12 18:00,20,야간,토,1,8,2,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14621,14621,2014,2014-07-15 04:00,30,야간,화,2,6,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14622,14622,2014,2014-07-10 20:00,40,야간,목,1,3,0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14623,14623,2014,2014-07-20 10:00,20,주간,일,1,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN